#!/bin/sh

set -e

if [ "$(uname -s)" != "Darwin" ]; then
  echo "Exiting: we are not a mac"
  exit 1
fi

if [ -d "/Applications/Atom.app" ]; then
  echo "Exiting: directory exists: /Applications/Atom.app"
  exit 1
fi

echo "Downloading... atom-mac.zip"
curl -L https://atom.io/download/mac \
  >  atom-mac.zip
echo "Extracting... atom-mac.zip"
unzip atom-mac.zip
echo "Moving Atom.app --> /Applications/Atom.app"
mv Atom.app /Applications
echo "Removing atom-mac.zip"
rm atom-mac.zip

bin/atom-add-project
bin/atom-package-install
