#!/bin/sh

mkdir -p zsh/bundle/bin
curl -L https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh \
  >  zsh/bundle/antigen.zsh
curl -L https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh \
  >  zsh/bundle/bin/antigen.zsh

mkdir -p ~/.config
git clone https://github.com/chriskempson/base16-shell.git \
  ~/.config/base16-shell
